---
apiVersion: v1
kind: service
metadata:
  name: postgres-service
  labels:
    author: naveen
    type: webserver
spec:
 type: ClusterIP
 selector:
   author: naveen
   name: postgres-pod
   ports:
     - targetPort: 5432
       port: 5432
...

