---
apiVersion: v1
kind: pod
metadata:
  name: postgres-pod
  labels:
    author: naveen
    name: postgres-pod
spec:
  containers:
    - name: postgres-app
      image: postgres
      ports:
       - containerPort: 5432


...

