---
apiVersion: v1
kind: pod
metadata:
  name: result-pod
  labels:
    author: naveen
    type: webserver
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
       - containerPort: 80


...
