---
apiVersion: v1
kind: service
metadata:
  name: result-service
  labels:
    author: naveen
    type: webserver
spec:
 type: loadBalancer
 selector:
   author: naveen
   name: result-pod
   ports:
     - targetPort: 80
       port: 80
...


