
apiVersion: v1
kind: pod
metadata:
  name: voting-pod
  labels:
    author: naveen
    name: voting-pod
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80


...
---