---
apiVersion: v1
kind: service
metadata:
  name: voting-service
  labels:
    author: naveen
    type: webserver
spec:
 type: LoadBalancer
 selector:
   author: naveen
   name: voting-pod
   ports:
     - targetPort: 80
       port: 80

...