---
apiVersion: v1
kind: pod
metadata:
  name: worker-pod
  labels:
    author: naveen
    name: worker-pod
spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker




...

